//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VectorEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ItemAbout {
            get {
                return ResourceManager.GetString("ItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string ItemCircle {
            get {
                return ResourceManager.GetString("ItemCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Color.
        /// </summary>
        internal static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ItemExit {
            get {
                return ResourceManager.GetString("ItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string ItemLoad {
            get {
                return ResourceManager.GetString("ItemLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string ItemRect {
            get {
                return ResourceManager.GetString("ItemRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ItemSave {
            get {
                return ResourceManager.GetString("ItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop.
        /// </summary>
        internal static string ItemStartStop {
            get {
                return ResourceManager.GetString("ItemStartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string MenuAnim {
            get {
                return ResourceManager.GetString("MenuAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLang {
            get {
                return ResourceManager.GetString("MenuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project by: Plamen Kostov.
        /// </summary>
        internal static string MsgAbout {
            get {
                return ResourceManager.GetString("MsgAbout", resourceCulture);
            }
        }
    }
}
